name: workout_pro
description: A minimalist cross-platform workout tracker
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Core Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  google_sign_in: ^7.1.1

  # Routing & State
  go_router: ^16.1.0
  provider: ^6.1.4

  # UI & Theming
  flutter_animate: ^4.5.2
  google_fonts: ^6.1.0
  fl_chart: ^1.0.0
  cached_network_image: ^3.2.3
  shared_preferences: ^2.2.1

  # Preview & Debug
  device_preview: ^1.1.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  fake_cloud_firestore: ^3.0.2

  # Optional BDD
  gherkin: ^3.1.0
  golden_toolkit: ^0.15.0

  
dependency_overrides:
  async: ^2.13.0
  fake_async: ^1.3.3
  vm_service: ^15.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
