// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// Default [FirebaseOptions] for use with your Firebase apps.
//
// Example:
// ```dart
// import 'firebase_options.dart';
// // ...
// await Firebase.initializeApp(
//   options: DefaultFirebaseOptions.currentPlatform,
// );
// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbE0zz8MtE8BeMrZFIFxnisV4zORKV2tk',
    appId: '1:528799096394:web:93f1256ab1f1b67b9010b3',
    messagingSenderId: '528799096394',
    projectId: 'fitness-tracking-app-4c4c4',
    authDomain: 'fitness-tracking-app-4c4c4.firebaseapp.com',
    storageBucket: 'fitness-tracking-app-4c4c4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArDwMYQ_PDI2xLPJtLgsy1zhNgKwTd_q4',
    appId: '1:528799096394:android:0623db17afda0b609010b3',
    messagingSenderId: '528799096394',
    projectId: 'fitness-tracking-app-4c4c4',
    storageBucket: 'fitness-tracking-app-4c4c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD2JaNpL0oyVEI562BVmRSlKg4Gj_uUiA',
    appId: '1:528799096394:ios:6cf104f1995c33249010b3',
    messagingSenderId: '528799096394',
    projectId: 'fitness-tracking-app-4c4c4',
    storageBucket: 'fitness-tracking-app-4c4c4.firebasestorage.app',
    iosBundleId: 'com.example.workoutPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD2JaNpL0oyVEI562BVmRSlKg4Gj_uUiA',
    appId: '1:528799096394:ios:6cf104f1995c33249010b3',
    messagingSenderId: '528799096394',
    projectId: 'fitness-tracking-app-4c4c4',
    storageBucket: 'fitness-tracking-app-4c4c4.firebasestorage.app',
    iosBundleId: 'com.example.workoutPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbE0zz8MtE8BeMrZFIFxnisV4zORKV2tk',
    appId: '1:528799096394:web:98ce30088da304839010b3',
    messagingSenderId: '528799096394',
    projectId: 'fitness-tracking-app-4c4c4',
    authDomain: 'fitness-tracking-app-4c4c4.firebaseapp.com',
    storageBucket: 'fitness-tracking-app-4c4c4.firebasestorage.app',
  );
}
